import sys
sys.path.append("C:/Users/azgardan/Data_Migration_project/data_migration/scripts/utils")
from faker import Faker
import faker_commerce
from sqlalchemy import text
from database_utils import get_oracle_connection, establish_oracle_ssh_tunnel
from file_utils import load_credentials

credentials = load_credentials()
fake = Faker()
fake.add_provider(faker_commerce.Provider)


def generate_fake_data(num_rows):
    try:
        ssh_tunnel = establish_oracle_ssh_tunnel(credentials)
        print("Oracle SSH tunnel established")
        session = get_oracle_connection(credentials, ssh_tunnel)
        print("Connected to Oracle database")


        reset_id_queries = [
            "ALTER TABLE regions MODIFY (region_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE locations MODIFY (location_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE warehouses MODIFY (warehouse_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE employees MODIFY (employee_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE warehouses MODIFY (warehouse_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE product_categories MODIFY (category_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE products MODIFY (product_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE orders MODIFY (order_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE customers MODIFY (customer_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE contacts MODIFY (contact_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)",
            "ALTER TABLE employees MODIFY (employee_id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1)"

        ]

        for query in reset_id_queries:
            session.execute(text(query))

        generated_product_id = set()
        generated_order_item_ids = set()

        # Insert fake data into regions table
        regions_data = [{'region_name': fake.word()} for _ in range(num_rows)]
        session.execute(text("INSERT INTO regions (region_name) VALUES (:region_name)"), regions_data)
        print('regions done')

        # Insert fake data into countries table
        for _ in range(num_rows):

            session.execute(text("""
                INSERT INTO countries (country_id, country_name, region_id) 
                VALUES (:country_id, :country_name, :region_id)
                """),
                    dict(country_id=fake.country_code(),
                    country_name=fake.country(),
                    region_id=fake.random_int(min=1, max=num_rows))
                    )
        print('countries done')

        # Insert fake data into locations table
        for _ in range(num_rows):
            session.execute(text("""
                INSERT INTO locations (address, postal_code, city, state, country_id) 
                VALUES (:address, :postal_code, :city, :state, :country_id)
                """),
                dict(address=fake.address(),
                    postal_code=fake.zipcode(),
                    city=fake.city(),
                    state=fake.state(),
                    country_id=fake.country_code()))
        print('locations done')

        # Insert fake data into warehouses table
        for _ in range(num_rows):
            session.execute(text("""
                INSERT INTO warehouses (warehouse_name, location_id) 
                VALUES (:warehouse_name, :location_id)
                """),
                    dict(warehouse_name=fake.word(),
                        location_id=fake.random_int(min=1, max=num_rows)))
        print('warehouses done')
            
        for _ in range(num_rows):
            session.execute(text("""INSERT INTO product_categories (category_name) 
                                VALUES (:category_name)
                                """),
                                dict(category_name=fake.ecommerce_category()))
        print('product_categories done')
        
        for _ in range(num_rows):
            session.execute(text("""INSERT INTO products (product_name, description, standard_cost, list_price, category_id)
                                 VALUES (:product_name, :description, :standard_cost, :list_price, :category_id)
                                 """),
                                 dict(
                                    product_name=fake.ecommerce_name(),
                                    description=fake.word(),
                                    standard_cost=fake.random_int(min=10, max=50),
                                    list_price=fake.random_int(min=100, max=500),
                                    category_id=fake.random_int(min=1, max=num_rows)))
        print('products done')
            
        for _ in range(num_rows):

            product_id = None
            while product_id is None or product_id in generated_product_id:
                product_id = fake.random_int(min=1, max=num_rows)
            
            generated_product_id.add(product_id)
            session.execute(text("""INSERT into inventories (product_id, warehouse_id, quantity)
                                 VALUES (:product_id, :warehouse_id, :quantity)"""),

                                 dict(
                                     product_id=product_id,
                                     warehouse_id=fake.random_int(min=1, max=num_rows),
                                     quantity=fake.random_int()))
        print('inventories done')

        for _ in range(num_rows):
            order_id = None
            item_id = None
            while order_id is None or item_id is None or (order_id, item_id) in generated_order_item_ids:
                order_id = fake.random_int(min=1, max=num_rows)
                item_id = fake.random_int(min=1, max=num_rows)
            
            generated_order_item_ids.add((order_id, item_id))
            session.execute(text("""INSERT INTO order_items (order_id, item_id, product_id, quantity, unit_price)
                                VALUES (:order_id, :item_id, :product_id, :quantity, :unit_price)
                                """),
                                dict(
                                    order_id=order_id,
                                    item_id=item_id,
                                    product_id=fake.random_int(min=1, max=num_rows),
                                    quantity=fake.random_int(),
                                    unit_price=fake.random_int(min=100, max=500)))
        print('order_items done')

        for _ in range(num_rows):
            session.execute(text("""INSERT INTO orders (customer_id, status, salesman_id, order_date)
                                 VALUES (:customer_id, :status, :salesman_id, :order_date)
                                """),
                                dict(
                                    customer_id=fake.random_int(min=1, max=num_rows),
                                    status=fake.word(),
                                    salesman_id=fake.random_int(min=1, max=num_rows),
                                    order_date=fake.date_this_decade()))
        print('orders done')
        for _ in range(num_rows):
            session.execute(text("""INSERT INTO customers (name, address, website, credit_limit)
                                 
                                VALUES (:name, :address, :website, :credit_limit)
                                """),
                                dict(
                                    name=fake.name(),
                                    address=fake.address(),
                                    website=fake.word(),
                                    credit_limit=fake.random_int(min=1000, max=5000)))
        print('customers done')

        for _ in range(num_rows):
            session.execute(text("""INSERT INTO contacts (first_name, last_name, email, phone, customer_id)
                                 
                                VALUES (:first_name, :last_name, :email, :phone, :customer_id)
                                """),
                                dict(
                                    first_name=fake.first_name(),
                                    last_name=fake.last_name(),
                                    email=fake.email(),
                                    phone=fake.phone_number(),
                                    customer_id=fake.random_int(min=1, max=num_rows)))
        print('contacts done')


        # Insert fake data into employees table
        for _ in range(num_rows):
            session.execute(text("""
                INSERT INTO employees (first_name, last_name, email, phone, hire_date, manager_id, job_title) 
                VALUES (:first_name, :last_name, :email, :phone, :hire_date, :manager_id, :job_title)
                """),
                dict(first_name=fake.first_name(),
                    last_name=fake.last_name(),
                    email=fake.email(),
                    phone=fake.phone_number(),
                    hire_date=fake.date_this_decade(),
                    manager_id=fake.random_int(min=1, max=num_rows),  # Assuming manager_id exists
                    job_title=fake.job()))
        print('employees done')

        # Commit the changes
        session.commit()

    except Exception as e:
        print(f"An error occurred: {str(e)}")

    finally:
        # Close the session and stop the SSH tunnel, regardless of success or failure
        try:
            if 'ssh_tunnel' in locals() and ssh_tunnel is not None:
                ssh_tunnel.stop()
                print("Oracle SSH Tunnel stopped.")
        except Exception as e:
            print(f"Error stopping Oracle SSH Tunnel: {str(e)}")

        try:
            if 'session' in locals() and session is not None:
                session.close()
                print("Oracle session closed.")
        except Exception as e:
            print(f"Error closing Oracle session: {str(e)}")




def delete_fake_data(table_names):
    try:

        ssh_tunnel = establish_oracle_ssh_tunnel(credentials)
        session = get_oracle_connection(credentials, ssh_tunnel)

        # Insert fake data into regions table
        for table_name in table_names:
            session.execute(text(f"DELETE FROM {table_name}"))
        session.commit()

    except Exception as e:
        print(f"An error occurred: {str(e)}")

    finally:
        # Close the session and stop the SSH tunnel, regardless of success or failure
        try:
            if 'ssh_tunnel' in locals() and ssh_tunnel is not None:
                ssh_tunnel.stop()
                print("Oracle SSH Tunnel stopped.")
        except Exception as e:
            print(f"Error stopping Oracle SSH Tunnel: {str(e)}")

        try:
            if 'session' in locals() and session is not None:
                session.close()
                print("Oracle session closed.")
        except Exception as e:
            print(f"Error closing Oracle session: {str(e)}")



def update_tables(table_name, set_values, conditions):
    try:
        ssh_tunnel = establish_oracle_ssh_tunnel(credentials)
        session = get_oracle_connection(credentials, ssh_tunnel)

         # Generate the SET clause for the update statement
        set_clause = ', '.join([f"{column} = :{column}" for column in set_values.keys()])

        # Generate the WHERE clause for the update statement
        where_clause = ' AND '.join([f"{column} = :{column}" for column in conditions.keys()])

        # Construct the SQL update statement
        update_query = text(f"UPDATE {table_name} SET {set_clause} WHERE {where_clause}")

        # Execute the update statement with the provided values
        session.execute(update_query, {**set_values, **conditions})

        # Commit the changes
        session.commit()

        print(f"Table '{table_name}' updated successfully.")

    except Exception as e:
            print(f"An error occurred: {str(e)}")

    finally:
            # Close the session and stop the SSH tunnel, regardless of success or failure
            try:
                if 'ssh_tunnel' in locals() and ssh_tunnel is not None:
                    ssh_tunnel.stop()
                    print("Oracle SSH Tunnel stopped.")
            except Exception as e:
                print(f"Error stopping Oracle SSH Tunnel: {str(e)}")

            try:
                if 'session' in locals() and session is not None:
                    session.close()
                    print("Oracle session closed.")
            except Exception as e:
                print(f"Error closing Oracle session: {str(e)}")


